version: '3.8'

services:
  pgvector-db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pgvector-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: vectordb-test
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
